# Generated by Django 4.2.6 on 2023-10-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=10, null=True, verbose_name=''),
        ),
    ]
