# Generated by Django 4.2.5 on 2023-10-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
